name: Update scs-frontend-config git repository
description: Updates the image tag of the given stage in an scs frontend repository

inputs:
  repository:
    description: The repository to update
    required: true

  ref:
    description: The branch to update
    required: true
  
  token:
    description: The token to use for checkout
    required: true

  docker-image-tag:
    description: The tag of the docker image build
    required: true

  yaml-path:
    description: The the path of the yaml file containing the image tag
    required: true

runs:
  using: composite
  steps:
    - name: Install yq
      shell: bash
      env:
        VERSION: v4.14.1
        BINARY: yq_linux_amd64
      run: |
        mkdir -p tools
        wget https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY}.tar.gz -O - |\
        tar xz && mv ${BINARY} tools/yq

    - name: Checkout ${{ inputs.repository }}
      uses: github/codeql-action/checkout@v2
      with:
        repository: ${{ inputs.repository }}
        token: ${{ inputs.token }}
        ref: ${{ inputs.ref }}

    - name: Set up git config
      shell: bash
      working-directory: scs
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "swe@interdiscount.ch"
    
    - name: Set image.tag to ${{ inputs.docker-image-tag }}
      shell: bash
      working-directory: scs
      run: |
        export IMAGE_TAG="${{ inputs.docker-image-tag }}"
        ../tools/yq eval -i '.spec.tags = strenv(IMAGE_TAG)' '${{ inputs.yaml-path }}'

    - name: Update and push git
      shell: bash
      working-directory: scs
      run: |
        git add "${{ inputs.yaml-path }}"
        git commit -m "chore: upgraded image tag to ${{ inputs.docker-image-tag }}"
        git push https://gitea.hs-gc.coop.ch/container-sync/interdiscount-sap-pubsub-adapter.git HEAD:${{ inputs.ref }}