name: Update frontend scs git repository
description: Updates the image tag of the given stage in the scs frontend repository

inputs:
  repository:
    description: The frontend scs repository to update
    required: true
  
  token:
    description: The token to use for checkout
    required: true

  docker-image-tag:
    description: The tag of the docker image build
    required: true

  stage:
    description: The stage to deploy to (development, acceptance, production)
    required: true

runs:
  using: composite
  steps:
    - name: Install yq
      shell: bash
      env:
        VERSION: v4.14.1
        BINARY: yq_linux_amd64
      run: |
        mkdir -p tools
        wget https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY}.tar.gz -O - |\
        tar xz && mv ${BINARY} tools/yq

    - name: Checkout ${{ inputs.repository }}
      uses: actions/checkout@v2
      with:
        repository: ${{ inputs.repository }}
        token: ${{ inputs.token }}
        path: 'scs'
        ref: 'main'

    - name: Set up git config
      shell: bash
      working-directory: scs
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
    
    - name: Set image.tag to ${{ inputs.docker-image-tag }}
      shell: bash
      working-directory: scs
      run: |
        ../tools/yq eval -i ".image.tag = ${{ inputs.docker-image-tag }}" "scs-frontend/values-${{ inputs.stage }}.yaml"

    - name: Update and push git
      shell: bash
      working-directory: scs
      run: |
        git add "scs-frontend/values-${{ inputs.stage }}.yaml"
        git commit -m "chore: upgraded image tag of ${{ inputs.stage }} to ${{ inputs.docker-image-tag }}"
        git push