name: Update scs-frontend-config git repository
description: Updates the image tag of the given stage in the scs frontend repository

inputs:
  shop:
    description: The shop to update
    required: true
  
  token:
    description: The token to use for checkout
    required: true

  docker-image-tag:
    description: The tag of the docker image build
    required: true

  stage:
    description: The stage to deploy to (development, acceptance, production)
    required: true

runs:
  using: composite
  steps:
    - name: Install yq
      shell: bash
      env:
        VERSION: v4.14.1
        BINARY: yq_linux_amd64
      run: |
        mkdir -p tools
        wget https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY}.tar.gz -O - |\
        tar xz && mv ${BINARY} tools/yq

    - name: Checkout ${{ inputs.repository }}
      uses: actions/checkout@v2
      with:
        repository: interdiscount/scs-frontend-config
        token: ${{ inputs.token }}
        path: 'scs'
        ref: 'main'

    - name: Set up git config
      shell: bash
      working-directory: scs
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
    
    - name: Set image.tag to ${{ inputs.docker-image-tag }}
      shell: bash
      working-directory: scs
      run: |
        export IMAGE_TAG="${{ inputs.docker-image-tag }}"
        ../tools/yq eval -i '.image.tag = strenv(IMAGE_TAG)' '${{ inputs.shop }}/image-${{ inputs.stage }}.yaml'
    - name: Update and push git
      shell: bash
      working-directory: scs
      run: |
        git add "${{ inputs.shop }}/image-${{ inputs.stage }}.yaml"
        git commit -m "chore: upgraded image tag of ${{ inputs.stage }} to ${{ inputs.docker-image-tag }}"
        git push